// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErxdOIhmSlYv6LmdB-1jDIXAQVJZ6v4E',
    appId: '1:210490835574:web:347190d2ca212153a65557',
    messagingSenderId: '210490835574',
    projectId: 'kinomania-d3c43',
    authDomain: 'kinomania-d3c43.firebaseapp.com',
    storageBucket: 'kinomania-d3c43.appspot.com',
    measurementId: 'G-DYKG01HLJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpcUFXSd3QheK4477ZELPwFB5yE2HKJU',
    appId: '1:210490835574:android:b389d2b44f3e352ca65557',
    messagingSenderId: '210490835574',
    projectId: 'kinomania-d3c43',
    storageBucket: 'kinomania-d3c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRS7L3xXMbXFtS_8p1XCpO7qj940Dn6I',
    appId: '1:210490835574:ios:d9948bc9f3f2a14ba65557',
    messagingSenderId: '210490835574',
    projectId: 'kinomania-d3c43',
    storageBucket: 'kinomania-d3c43.appspot.com',
    iosBundleId: 'com.example.kinoMania2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRS7L3xXMbXFtS_8p1XCpO7qj940Dn6I',
    appId: '1:210490835574:ios:60ce7183f74de56ca65557',
    messagingSenderId: '210490835574',
    projectId: 'kinomania-d3c43',
    storageBucket: 'kinomania-d3c43.appspot.com',
    iosBundleId: 'com.example.kinoMania2.RunnerTests',
  );
}
